-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Autobuses"
(
    "Id_autobus" serial NOT NULL,
    precio numeric(10, 4),
    PRIMARY KEY ("Id_autobus")
);

CREATE TABLE IF NOT EXISTS public."Rutas"
(
    id_rutas serial,
    id_autobus integer NOT NULL,
    id_conductor integer NOT NULL,
    id_lugares integer NOT NULL,
    fecha date NOT NULL,
    PRIMARY KEY (id_rutas)
);

CREATE TABLE IF NOT EXISTS public."Conductores"
(
    id_conductor serial NOT NULL,
    nombre character varying(60) NOT NULL,
    edad integer,
    PRIMARY KEY (id_conductor)
);

CREATE TABLE IF NOT EXISTS public."Lugares"
(
    id_lugares serial NOT NULL,
    nombre character varying,
    PRIMARY KEY (id_lugares)
);

ALTER TABLE IF EXISTS public."Rutas"
    ADD CONSTRAINT fk_rutas_autobuses FOREIGN KEY (id_autobus)
    REFERENCES public."Autobuses" ("Id_autobus") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rutas"
    ADD CONSTRAINT fk_rutas_lugares FOREIGN KEY (id_lugares)
    REFERENCES public."Lugares" (id_lugares) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rutas"
    ADD CONSTRAINT fk_rutas_conductores FOREIGN KEY (id_conductor)
    REFERENCES public."Conductores" (id_conductor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;